name: Android Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          check-latest: true

      - name: Install dependencies
        run: npm install

      - name: Build Web Assets
        run: npm run build

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Fix Permissions and Build
        run: |
          cd android
          # تعيين الصلاحيات لجميع الملفات في مجلد الأندرويد لضمان عدم وجود عوائق
          chmod -R +x .
          # تشغيل البناء باستخدام bash بشكل مباشر
          /bin/bash ./gradlew assembleDebug --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
